
    <div class="">
        <div class="container">
            <div class="" id="pagew"></div>
        </div>
    </div>

    
    <section class="py-5">
        <div class="container">
            <h3 class="text-center mb-3">Terms Of Use</h3>
            <big class="d-block text-center mb-5"><p>PLEASE READ THIS DOCUMENT CAREFULLY! IT CONTAINS VERY IMPORTANT INFORMATION ABOUT YOUR RIGHTS AND OBLIGATIONS, AS WELL AS LIMITATIONS AND EXCLUSIONS THAT MAY APPLY TO YOU.</p><p>These Terms of Sale apply to your purchase of classified ad listings (“ Ad(s)”) on cars2day.com (the “Website”) that are offered through cars2day Sell Your Car service (“Service”). By placing an order for any   Ads appearing through the Service, you accept and are bound by the terms and conditions in these Terms of Sale. Additionally, you agree to our Visitor Agreement and Privacy Statement, each of which is incorporated herein by reference. If you do not wish to be bound by these terms and conditions, you should not place an order for an Ad through this Service.</p></big>
            
            <div class="coockycontent mb-5 pb-5">
                <h4>A) General Rules</h4>
                <div class="pb-3"><span>1.</span>		Ads are available only to those who want to list their personally owned vehicle(s) for sale. Cars2day and its affiliates reserve the right (but assume no obligation) to delete, move, or edit, without refund, any  Ads that come to our attention that we consider unacceptable or inappropriate, whether for legal or other reasons.</div>
                <div class="pb-3"><span>2.</span>span>		You may not list more than five (5) vehicles annually through the Service. Individuals who seek to list more than five (5) vehicles on the Website, as well as all dealers, brokers, businesses or persons otherwise engaged in the commercial sale of vehicles or offering vehicles for sale as a paid service to a seller or title holder, must make other arrangements with us and our affiliates to place such commercial ads. To find out more about dealer listings and advertising opportunities on Cars2day and/or our affiliated products and services, please visit our Cars2day Dealer page.</div>
                <div class="pb-3"><span>3.</span>		By using the Service, you represent that (1) you are at least eighteen (18) years old, (2) you are not a motor vehicle dealer, broker, business or person otherwise engaged in the commercial sale of vehicles, (3) you are not offering vehicles for sale as a paid service to a seller or title holder of a vehicle, and that you are not listing a vehicle for sale in your capacity as an employee or representative of a dealer, broker, business or person otherwise engaged in the commercial sale of vehicles, (4) you are not acting as a broker or agent for someone who placed an Ad through the Service, and (5) neither you nor anyone acting on your behalf will list more than five (5) vehicles for sale simultaneously through the Service.</div>
                <div class="pb-3"><span>4.</span>		Cars2day and its affiliates reserve the right to deny the use of their respective products and services, which includes the Website, to anyone who does not comply with these Terms of Sale or who otherwise the use such online and/or offline products or services, including the Website, in a manner we consider inappropriate.</div>
                <div class="pb-3"><span>5.</span>		Used car listings on the Website include vehicles that have been “certified” as meeting certain standards established by manufacturers and/or dealers in connection with their pre-owned vehicle programs. Ads purchased by through the Service are not eligible for, and will not appear in, any “certified” area of the Website or any similar area within our affiliated products and services. Only vehicles certified by the automobile manufacturers and/or dealers or certified agencies with which we have partnerships may be labelled as “Certified” on the Website.</div>
                <h4 class="mt-5">B) Using the Sell Your Car Service</h4>
                <div class="pb-3"><span>6.</span>		When you offer a vehicle for sale through the Service, you must be prepared to sell that vehicle at the price at which, and the terms on which, you’ve listed it. You must have possession of the actual vehicle listed at the time of creating ads and the ability to transfer the title.</div>
                <div class="pb-3"><span>7.</span>		To list a vehicle for sale through the Service, you are required to provide certain identifying and contact information. The information in your  Ad must accurately identify you and the method of contact must permit buyers to communicate directly with you. You may not include in your  Ad the name, telephone number or email address of any agent, broker or dealer.</div>
                <div class="pb-3"><span>8.</span>		You may not charge any potential buyer for information about any vehicle listed for sale on Cars2day, nor may you use the Website to promote, without our prior written permission, any other website, product or service. Any rights and obligations you maintain under these Terms of Sale to access and use the Service are personal to you. Consequently, you may not assign or delegate any such rights or obligations to any third party, which includes agents, brokers or dealers.</div>
                <div class="pb-3"><span>9.</span>		Ad(s) placed through the Service may not be used to advertise more than one (1) vehicle per  Ad purchased, regardless of the type of advertising package you select or the duration of its publication. For this reason, you may not edit your vehicle’s Year, Make, Model and VIN once you purchase your  Ad. Always double-check this information before submitting your  Ad. If you believe you made an error while submitting your vehicle’s Year, Make, Model or VIN, you must promptly contact Cars2day customer support at [[[[XXXXX]]]</div>
                <div class="pb-3"><span>10.</span> 	Responsibility for the information contained in your  Ad lies with you, the seller. You alone are responsible for the material you post online, and for the content of all messages transmitted through the Service.</div>
                <div class="pb-3"><span>11.</span>	Ad(s) poster especially undertakes that<br>a.	It is not a theft vehicle.<br>b.	No Speedometer is adjusted on vehicles.<br>c.	The Vehicle has all proper documents as per RTO Requirements.<br>d.	That the vehicle advertised is in possession at the time of posting of Ad</div>
                <h4 class="mt-5">C ) Quality Assurance</h4>
                <div class="pb-3"><span>12.</span>	Though we can’t monitor every ad that originates on or takes place through the Service, we may perform random quality assurance tests to confirm that sellers who offer vehicles for sale through the Service are prepared to sell the vehicles they advertise at the prices at which, and the terms on which, they advertise them.</div>
                <div class="pb-3"><span>13.</span>	Photos submitted as part of any  Ad placed through the Service must correspond to the actual vehicle being offered for sale. As part of our random quality assurance tests, if we encounter a photo that we believe does not accurately represent the actual vehicle you are offering for sale through the Service, we maintain the right to immediately remove such photo(s) and/or your corresponding  Ad. If you believe your photo(s) and/or your corresponding  Ad was removed in error, you may contact one of our customer service representatives by calling [[[XXXX]]]  customersupport@cars2day.com.</div>
                <div class="pb-3"><span>14.</span>	By using the Service, you agree to cooperate with these random quality assurance tests. If our tests reveal, or we otherwise learn, that you are engaging in “bait and switch” or other unfair or deceptive practices, Cars2day and/or its affiliates reserve the right to deny you use of the Service.</div>
                <div class="pb-3"><span>15.</span>	In connection with our efforts to combat fraud, some  Ads may be screened before being posted publicly. This process may delay the display of your  Ad for up to 24 hours from the time you submit your  Ad. If your  Ad does not appear on Cars2day after 24 hours, you should contact one of our customer service representatives by calling [XXXX] Mon.-Fri. 8 am-8 pm; Sat. 9am-7 pm IST or emailing customersupport@cars2day.com. As part of our effort to combat fraud, we may also screen any messages sent to sellers through the inquiry form in the Service.</div>
                <div class="pb-3"><span>16.</span>	Although Cars2day cannot monitor all the  Ads processed through the Service, we reserve the right (but assume no obligation) to delete, move, or edit, without refund, any ads, postings or other electronic communications that come to our attention that we consider unacceptable or inappropriate, whether for legal or other reasons.</div>
                <div class="pb-3"><span>17.</span>	By placing  Ads through the Service, you agree not to post or transmit any defamatory, abusive, obscene, threatening, misleading, or illegal material, or any other material that infringes on the rights of others or interferes with the ability of others to enjoy Cars2day or our affiliated products and services. Cars2day and our affiliates retain the right to deny access to anyone who we believe has violated these Terms of Sale, our Visitor Agreement, and/or our Privacy Statement.</div>
                <div class="pb-3"><span>18.</span>	Except as otherwise provided under these Terms of Sale, Cars2day and our affiliates will not, in the ordinary course of business, review the content of private electronic messages that are not addressed to Cars2day or any of our affiliates. However, Cars2day and our affiliates may occasionally release information concerning such communications when release is appropriate to comply with the law (including disclosure in response to a request from a law enforcement agency), to enforce these Terms of Sale or to protect the rights, property or safety of visitors to the Website, our advertisers, our affiliates, the public or Cars2day.</div>
                <h4 class="mt-5">D)  Fees, Payments and Refunds; Premiums, Promotions 		and Free Services</h4>
                <div class="pb-3"><span>19.</span>	By placing a  Ad through the Service, you agree to pay all fees and charges incurred at the rates in effect for the billing period covering the advertising package(s) you obtain, regardless of whether your vehicle sells as a result of the ad package(s) you purchase, subject to Section 4E(3) below. All fees and charges will be applied against the form of payment you provide as part of the ad selection process and you agree to pay such fees and charges. You also agree to pay any applicable taxes relating to your use of the Service. At its sole discretion, Cars2day reserves the right at any time to offer the Service at a discount or to provide premiums and promotions as incentives, up to and including free Sell Your Car services.</div>
                <div class="pb-3"><span>20.</span>	Should Cars2day offer  Ads at no charge on the Website and/or via our call center(s), we may, at our sole discretion, offer these  Ads nationally, in a limited number of markets, to a limited number of advertisers, or for a limited period of time.</div>
                <div class="pb-3"><span>21.</span>	When you list a car for sale using any free advertising service that we may offer, you will be asked for information on the car you are selling and on how you can be contacted by potential buyers. We may also ask you for other personally identifying information for security purposes. We may use this information to contact you about your  Ad, or for marketing and other promotional purposes, including offers of additional paid ad services.</div><div class="pb-3"><span>22.</span>	You must use care when selecting your ad package and inputting information for your  Ad;  Ad fees are generally not refundable except as set forth in Section D20 below, even if you provide erroneous information or fail to sell your vehicle. Cars2day will reasonably assist you to correct certain mistakes made by you in placing your  Ad (for example, Year, Make, Model, or VIN). To make such corrections to your  Ad, please contact Cars2day.</div><div class="pb-3"><span>23.</span>	Except as provided for in Section D23, Cars2day and its affiliates will not provide any refund for any reason if Cars2day or one of its affiliates receives the request for a refund after your  Ad is published on the Website.</div><div class="pb-3"><span>24.</span>	You may be entitled to a refund or credit if you mistakenly order and pay for duplicate  Ads through the Service and seek to cancel and obtain a refund or credit on the duplicate  Ad only. You are not entitled and we cannot provide you a refund or credit on the original  Ad.</div>
                <div class="pb-3"><span>25.</span>	Cars2day and its affiliates will not provide a refund or credit for any  Ad for any reason other than as described   above, even if you contact us within 72 hours from the time we accept your order for a  Ad. For example, we cannot provide you a refund or credit if you change your mind about publishing your  Ad, its content or any enhancements you purchased in relation to your  Ad selection. You may incur an added charge if you wish to order enhancements (“Enhancements”) to your initial order for your  Ad. You are not entitled to a refund or credit if you wish to change to a less expensive ad package. We cannot provide you a refund or credit if you made mistakes while submitting your  Ad information or if you fail to receive any inquiries or offers to purchase your vehicle through the use of the Service. No refund or credit will be issued if you sold your vehicle through other means, except as provided for in Section 4F.</div><div class="pb-3"><span>26.</span>	Except as provided under above, while Cars2day and its affiliates will not provide you a refund or credit in cases where we have made mistakes in the connection with the publication of your  Ad(s), Cars2day will use reasonable efforts to correct any mistakes we might have made in placing your  Ad (i.e.: ads we reasonably determine are duplicative, or contain erroneous information); provided, that you contact Cars2day customer support within the first 72 hours from the time we accept your order for an Ad.</div><div class="pb-3"><span>27.</span>	If your  Ad on Cars2day was purchased through a third party source (for example, a newspaper or third party website), we do not have the authority to make any changes to your  Ad and we cannot provide you a credit or refund for such ads. You are not entitled to a refund or credit if you place an Ad on the Service through a third party source (for example, newspapers or third party websites) and you also place a similar or identical  Ad directly with Cars2day. Such ads are not considered “duplicates” and you will not be entitled to cancel any such ads nor will you be titled to a refund or credit of any fees or charges associated with any such ads.</div>
                <h4 class="mt-5">E) Vehicle Inspection Services</h4>
                <div class="pb-3 mb-5"><span>28.</span>	Certain ad packages available through the Service may offer you the ability to purchase a vehicle inspection from Cars2day or a third-party service provider for the vehicle you are selling. If you purchase such an inspection, you will receive a written inspection report that describes the results of the inspection from Cars2day or our service provider that performs the inspection. The inspection report reflects the subjective observations and opinions of the vehicle inspector and is not a warranty or guarantee of your vehicle’s condition. When the inspection is completed, you will have the opportunity to review the inspection report and decide whether to include it with your  Ad.</div>
                <div class="mb-5">BY ORDERING AN INSPECTION FOR YOUR  AD, YOU AGREE TO RELEASE AND DISCHARGE CARS2DAY, THE SERVICE PROVIDER PERFORMING THE INSPECTION SERVICE, AND THEIR RESPECTIVE AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND INSPECTION CONTRACTORS FROM ALL LIABILITY ARISING FROM THE INSPECTION OF YOUR VEHICLE OR YOUR DECISION TO PUBLISH (OR NOT TO PUBLISH) THE RESULTING INSPECTION REPORT IN YOUR  LISTING.
<br><br>
Without limiting to the above Section, if you purchase a vehicle inspection that is provided by our service provider, you agree that, in addition to these Terms of Sale, the inspection services, and use of any inspection report resulting from such services, may be subject to additional terms and conditions from that service provider.
</div>
                <h4>Disclaimer of Warranties, Limitation of Liability, and Indemnification</h4>
                <div class="mb-5">IF YOU RELY ON THE WEBSITE OR ANY INFORMATION, PRODUCT OR SERVICE AVAILABLE THROUGH THE WEBSITE, YOU DO SO AT YOUR OWN RISK. YOU UNDERSTAND THAT THERE MAY BE DELAYS, OMISSIONS, INTERRUPTIONS, INACCURACIES, AND/OR OTHER PROBLEMS WITH THE INFORMATION, PRODUCTS, AND SERVICES PUBLISHED ON OR PROMOTED OVER THE WEBSITE AND/OR THROUGH AFFILIATED PRODUCTS OR SERVICES. THE WEBSITE AND ANY AFFILIATED PRODUCTS AND SERVICES ARE PROVIDED TO YOU “AS IS.” CARS2DAY AND ITS AFFILIATES, AGENTS AND LICENSORS CANNOT AND DO NOT WARRANT THE ACCURACY, COMPLETENESS, CURRENTNESS, NONINFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OF THE INFORMATION AVAILABLE THROUGH THE WEBSITE OR ANY AFFILIATED PRODUCT OR SERVICE (OR ANY INFORMATION, GOODS OR SERVICES THAT ARE REFERRED TO, ADVERTISED OR PROMOTED ON, OR SOLD THROUGH THE WEBSITE), NOR DO WE OR THEY GUARANTEE THAT THE WEBSITE AND/OR ANY AFFILIATED PRODUCT OR SERVICE WILL BE ERROR FREE OR CONTINUOUSLY AVAILABLE, OR THAT THE WEBSITE WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
<br><br>
UNDER NO CIRCUMSTANCES WILL CARS2DAY OR ITS AFFILIATES, AGENTS OR LICENSORS BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DAMAGES OTHER THAN DIRECT DAMAGES, ARISING OUT OF YOUR USE OF THE WEBSITE OR ANY AFFILIATED PRODUCT OR SERVICE ASSOCIATED WITH OR OTHERWISE LINKED TO OR FROM THE WEBSITE, OR ADVERTISED OR PROMOTED ON THE WEBSITE, INCLUDING, WITHOUT LIMITATION, CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE, EXEMPLARY, OR OTHER DAMAGES OF ANY KIND (INCLUDING LOST REVENUES OR PROFITS, LOSS OF BUSINESS OR LOSS OF DATA), EVEN IF WE ARE ADVISED BEFOREHAND OF THE POSSIBILITY OF SUCH DAMAGES. YOU AGREE THAT THE LIABILITY OF CARS2DAY AND ITS AFFILIATES, AGENTS AND LICENSORS, IF ANY, ARISING OUT OF ANY KIND OF LEGAL CLAIM ARISING OUT OF OR OTHERWISE RELATED TO THE WEBSITE, THE SERVICE, AND/OR ANY AFFILIATED PRODUCTS OR SERVICES WILL NOT EXCEED THE AMOUNT YOU PAID, IF ANY, FOR THE USE OF THE WEBSITE OR THE USE OF THE SERVICE. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SOME OF THESE LIMITATIONS MAY NOT APPLY TO YOU.
<br><br>
YOU AGREE TO INDEMNIFY AND HOLD HARMLESS CARS2DAY, ITS AFFILIATES, AND THEIR RESPECTIVE EMPLOYEES, OWNERS, REPRESENTATIVES, AND LICENSEES AGAINST ANY AND ALL CLAIMS, OF WHATEVER NATURE, THAT ARISE OUT OF ANY  AD YOU PLACE OR ATTEMPT TO PLACE THROUGH THE SERVICE.
</div>
                <h4>Miscellaneous</h4>
                <div>These Terms of Sale are made in, and will be  subject to the jurisdiction of Chennai, India for all disputes arising out of or relating to these Terms of Sale or the use of the Service.
<br><br>
These Terms of Sale, together with the Cars2day Visitor Agreement and Privacy Statement, contains the entire agreement and understanding between you and Cars2day regarding the subject matter hereof, and supersedes all prior proposals, understandings and all other agreements, oral and written, between the parties relating to this subject matter. Cars2day reserves the right to modify these Terms of Sale from time to time and will post any such changes on the Website. Your use of the Service after Cars2day has posted such modifications to these Terms of Sale on the Website will constitute your assent to any such modifications.
</div>
                
                
            </div>

            
        </div>
    </section> 

    


